---
resources:
  - name: sample-react-site
    type: git
    source:
      uri: https://github.com/drewrm/sample-react-site.git
jobs:
  - name: build
    plan:
      - get: sample-react-site
        trigger: true
      - task: compile
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: node, tag: "8.8"}
          inputs:
            - name: sample-react-site
              path: .
          run:
            path: bash
            args:
              - -exc
              - |
                npm install -g yarn
                yarn install
                yarn run compile
