---
resources:
  - name: source
    type: git
    source:
      uri: https://github.com/drewrm/sample-react-site.git
    branch: master
jobs:
  - name: andrew-test
    plan:
      - get: source
        trigger: true
      - task: test-mc-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: node, tag: "7"}
          inputs:
            - name: source
              path: .
          run:
            path: bash
            args: 
              - -exc
              - |
                npm install -g yarn
                yarn install
                yarn run compile
